name: Deploy to EC2 (dist branch)

on:
  push:
    branches:
      - dist
  workflow_dispatch:  # This allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dist branch
        uses: actions/checkout@v3

      - name: Copy build files to EC2 using SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "dist/*"
          target: "/home/Gossip/"
          timeout: "300" # Increase overall timeout to 5 minutes
          command_timeout: "300"

      - name: Restart Web Server
        run: |
          sudo echo "${{ secrets.EC2_KEY }}" > /tmp/private_key.pem  # Write the key to a file
          sudo chmod 600 /tmp/private_key.pem  # Make the key file readable
          sudo ssh -i /tmp/private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo systemctl restart nginx"
