name: Deploy to EC2 and Restart Nginx

on:
  push:
    branches:
      - dist  # Trigger on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$EC2_KEY" > ~/.ssh/id_rsa  # Reference your private key secret here
        chmod 600 ~/.ssh/id_rsa  # Secure the key file

      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}  # GitHub secret for private key

    - name: Add EC2 host to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts  # EC2 host from secret

    - name: Deploy code to EC2
      run: |
        scp -r ./dist/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/Gossip/  # Copy files to EC2

    - name: Restart Nginx on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo systemctl restart nginx"  # Restart Nginx