name: Deploy to EC2 (dist branch)

on:
  push:
    branches:
      - dist
  workflow_dispatch:  # This allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the dist branch
      - name: Checkout dist branch
        uses: actions/checkout@v3

      # Step 2: Copy build files to EC2 using rsync
      - name: Deploy to EC2 using Rsync
        run: |
          echo "${{ secrets.EC2_KEY }}" > /tmp/private_key.pem  # Write the private key to a temporary file
          chmod 600 /tmp/private_key.pem  # Secure the key file
          rsync -avz -e "ssh -i /tmp/private_key.pem" dist/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/Gossip/

      # Step 3: Restart the Web Server
      - name: Restart Web Server
        run: |
          echo "${{ secrets.EC2_KEY }}" > /tmp/private_key.pem  # Write the private key to a temporary file
          chmod 600 /tmp/private_key.pem  # Secure the key file
          ssh -i /tmp/private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo systemctl restart nginx"
